server:
  ip: https://justforyou.ntub.edu.tw
  image:
    name: image
    path: 'C:\just-for-you\UploadFile\${server.image.name}\'
  file:
    name: file
    path: 'C:\just-for-you\UploadFile\${server.file.name}\'
  summary-token:
    value: ''
  emotion-token:
    value: ''
  topic-token:
    value: ''
  text-token:
    value: ''
  level-token:
    value: ''
  youtube-api-key:
    value: ""
logging:
  level:
    sqltiming: DEBUG
    resultsettable: DEBUG
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
just-for-you:
  mail:
    account: ntubimd112404@gmail.com
    password: ''